#!/bin/bash
function check_rc(){
        rc=$?
        echo ---------------------------------------
        if [[ $rc != 0 ]];
        then
                echo $1 ' FAILURE!'
                exit $rc
        else
                echo $1 ' SUCCESS!'
        fi
        echo ---------------------------------------
}

./Python_Files/merge_checklists.py -c Compliance_Database/ErrorManagementChecklist_Rev2.txt -c Compliance_Database/DataStreamingChecklist_Rev2.txt -c Compliance_Database/rev1_3_rio_chklist.txt -c Compliance_Database/rapidio_interop_checklist_rev2_2.txt -o Standards_Outlines/outline_1.3.txt  -o Standards_Outlines/outline_2.2.txt  -t Standards_Translations/translate_1.3to2.2.txt -t Standards_Translations/translate_2.2to3.2.txt -t Standards_Translations/translate_3.2to4.0.txt -t Standards_Translations/translate_4.0to4.1.txt -r Standards_Requirements/reqts_2.2.txt -r Standards_Requirements/reqts_3.2.txt -m Standards_Requirements/manual_reqts_3.2.txt -d Standards_Requirements/manual_drop_3.2.txt -r Standards_Requirements/reqts_4.0.txt -m Standards_Requirements/manual_reqts_4.0.txt -r Standards_Requirements/reqts_4.1.txt > Compliance_Database/merged_sorted_checklist.txt
check_rc 'MERGE all checklists'
./Python_Files/update_checklist_db.py -c Compliance_Database/merged_sorted_checklist.txt -d Compliance_Database/merged_sorted_db.txt > Compliance_Database/merged_sorted_db2.txt
check_rc 'UPDATE database'
mv Compliance_Database/merged_sorted_db2.txt Compliance_Database/merged_sorted_db.txt
check_rc 'Moved database file'
