#!/bin/bash
./parse_checklist.py -f Historic_Checklists/Error\ Management\ Checklist.xml -r 1.3 > Historic_Checklists/ErrorManagementChecklist.txt
 ./parse_checklist.py -f Historic_Checklists/Data\ Streaming\ Checklist.xml -r 1.3 > Historic_Checklists/DataStreamingChecklist.txt 
 ./parse_checklist.py -f Historic_Checklists/rev1_3_rio_chklst.xml -r 1.3 > Historic_Checklists/rev1_3_rio_chklist.txt


