#!/bin/bash
./parse_rapidio_standard.py -f Standards/RapidIO\ 1.3\ Specification\ Stack.xml -o -r test > Standards/outline_1.3.txt
./parse_rapidio_standard.py -f Standards/Rev_2.2_specification_stack.xml -o -r test > Standards/outline_2.2.txt
./parse_rapidio_standard.py -f Standards/RapidIO-Revision-3.2-Specification.xml -o -r test > Standards/outline_3.2.txt
./parse_rapidio_standard.py -f Standards/RapidIO-Specification-4.0.xml -o -r test > Standards/outline_4.0.txt

diff Standards/outline_1.3.txt Standards/outline_2.2.txt > Standards/1.3to2.2.txt 
diff Standards/outline_2.2.txt Standards/outline_3.2.txt > Standards/2.2to3.2.txt
diff Standards/outline_3.2.txt Standards/outline_4.0.txt > Standards/3.2to4.0.txt

