#!/bin/bash
./parse_checklist.py -f Historic_Checklists/Error\ Management\ Checklist.xml -r 1.3 > Historic_Checklists/ErrorManagementChecklist.txt
./parse_checklist.py -f Historic_Checklists/Data\ Streaming\ Checklist.xml -r 1.3 > Historic_Checklists/DataStreamingChecklist.txt
./parse_checklist.py -f Historic_Checklists/rev1_3_rio_chklst.xml -r 1.3 > Historic_Checklists/rev1_3_rio_chklist.txt
./parse_checklist.py -f Historic_Checklists/rapidio_interop_checklist_rev2_2.xml -r 2.2 -p 6 -t > Historic_Checklists/rev2_2_rio_chklist.txt
./merge_checklists.py -f Historic_Checklists/ErrorManagementChecklist.txt -f Historic_Checklists/DataStreamingChecklist.txt -f Historic_Checklists/rev1_3_rio_chklist.txt -f Historic_Checklists/rev2_2_rio_chklist.txt > Historic_Checklists/merged_sorted_checklist.txt
