#!/bin/bash
function check_rc(){
        rc=$?
        echo ---------------------------------------
        if [[ $rc != 0 ]];
        then
                echo $1 ' FAILURE!'
                exit $rc
        else
                echo $1 ' SUCCESS!'
        fi
        echo ---------------------------------------
}

./parse_rapidio_standard.py -f Standards/RapidIO\ 1.3\ Specification\ Stack.xml -e -r 1.3 > Standards/registers_1.3.txt 2>&1
check_rc registers_1.3
./parse_rapidio_standard.py -f Standards/Rev_2.2_specification_stack.xml -e -r 2.2 > Standards/registers_2.2.txt 2>&1
check_rc registers_2.2
./parse_rapidio_standard.py -f Standards/RapidIO-Revision-3.2-Specification.xml -e -r 3.2 > Standards/registers_3.2.txt 2>&1
check_rc registers_3.2
./parse_rapidio_standard.py -f Standards/RapidIO-Specification-4.0.xml -e -r 4.0 > Standards/registers_4.0.txt 2>&1
check_rc registers_4.0
./parse_rapidio_standard.py -f Standards/RapidIO-Specification-4-1.xml -e -r 4.1 > Standards/registers_4.1.txt 2>&1
check_rc registers_4.1

./create_register_summary.py -r Standards/registers_1.3.txt -r Standards/manual_registers_1.3.txt > Standards/register_summary_1.3.txt
check_rc 'Create 1.3 Register Summary text'

./make_document.py -t Standards/register_summary_1.3.txt -w Standards/register_summary_1.3.docx
check_rc 'Create 1.3 Register Summary MS Word file'

./create_register_summary.py -r Standards/registers_1.3.txt -r Standards/registers_2.2.txt -r Standards/manual_registers_2.2.txt -t Standards/translate_1.3to2.2.txt > Standards/register_summary_2.2.txt
check_rc 'Create 2.2 Register Summary text'

./make_document.py -t Standards/register_summary_2.2.txt -w Standards/register_summary_2.2.docx
check_rc 'Create 2.2 Register Summary MS Word file'

./create_register_summary.py -r Standards/registers_3.2.txt -r Standards/manual_registers_3.2.txt -t Standards/translate_1.3to2.2.txt -t Standards/translate_2.2to3.2.txt > Standards/register_summary_3.2.txt
check_rc 'Create 3.2 Register Summary text'

./make_document.py -t Standards/register_summary_3.2.txt -w Standards/register_summary_3.2.docx
check_rc 'Create 3.2 Register Summary MS Word file'
