#!/usr/bin/env python
# -*- coding: latin-1 -*-
"""
    File header and line header constants.

"""
OUTLINE_HEADER = "Revision, Part, Chapter, Section"

REQT_NUM_OFFSET_NONE = 0
REQT_NUM_OFFSET_CHKLIST = 1000
REQT_NUM_OFFSET_MANUAL = 5000
REQT_NUM_OFFSET_AUTO = 7000
REQT_NUM_OFFSET_SPEC_MAX = REQT_NUM_OFFSET_CHKLIST - 1
REQT_NUM_OFFSET_CHKLIST_MAX = REQT_NUM_OFFSET_MANUAL - 1
REQT_NUM_OFFSET_MANUAL_MAX = REQT_NUM_OFFSET_AUTO - 1

REQUIREMENTS_HEADER = "Revision, Part, Chapter, Section, Type, Reqt_Num, Sentence"
TOK_IDX_REQTS_REVISION = 0
TOK_IDX_REQTS_PART = 1
TOK_IDX_REQTS_CHAPTER = 2
TOK_IDX_REQTS_SECTION = 3
TOK_IDX_REQTS_TYPE = 4
TOK_IDX_REQTS_REQT_NUM = 5
TOK_IDX_REQTS_SENTENCE = 6
REQUIREMENTS_HEADER_TOKEN_COUNT = TOK_IDX_REQTS_SENTENCE + 1

MERGED_CHECKLIST_SPEC_REVS = "Keys: "
MERGED_CHECKLIST_SORTED_SPEC_REVS = "Keys sorted: "

CHECKLIST_HEADER = "Sentence, Sentence_num, Type, Revision, Part, Chapter, Section, FileName, Table_Name, Checklist_ID, Optional"
TOK_IDX_CHK_H_SENTENCE = 0
TOK_IDX_CHK_H_SENTENCE_NUM = 1
TOK_IDX_CHK_H_TYPE = 2
TOK_IDX_CHK_H_REVISION = 3
TOK_IDX_CHK_H_PART = 4
TOK_IDX_CHK_H_CHAPTER = 5
TOK_IDX_CHK_H_SECTION = 6
TOK_IDX_CHK_H_FILENAME = 7
TOK_IDX_CHK_H_TABLE_NAME = 8
TOK_IDX_CHK_H_CHECKLIST_ID = 9
TOK_IDX_CHK_H_OPTIONAL = 10
CHECKLIST_HEADER_TOKEN_COUNT = TOK_IDX_CHK_H_OPTIONAL + 1

CHECKLIST_HEADER_REV_FORMAT = "%s, %s, %s_Part, %s_Chapter, %s_Section"
TOK_IDX_MRG_CHK_H_FIRST_REV = 11
TOK_IDX_MRG_CHK_H_FIRST_PART = 12
TOK_IDX_MRG_CHK_H_FIRST_CHAP = 13
TOK_IDX_MRG_CHK_H_FIRST_SECN = 14
TOK_IDX_MRG_CHK_H_TOK_COUNT = (TOK_IDX_MRG_CHK_H_FIRST_SECN -
                               TOK_IDX_MRG_CHK_H_FIRST_REV + 1)
TOK_IDX_MRG_CHK_H_MIN_TOK_COUNT = TOK_IDX_MRG_CHK_H_FIRST_SECN + 1

DATABASE_HEADER = "Const_Reference, Sentence, Sentence_num, Type, Revision, Part, Chapter, Section, FileName, Table_Name, Checklist_ID, Optional, Status"

TOK_IDX_DB_H_CONST_REF = 0
TOK_IDX_DB_H_SENTENCE = TOK_IDX_CHK_H_SENTENCE + 1
TOK_IDX_DB_H_SENTENCE_NUM = TOK_IDX_CHK_H_SENTENCE_NUM + 1
TOK_IDX_DB_H_TYPE = TOK_IDX_CHK_H_TYPE + 1
TOK_IDX_DB_H_REVISION = TOK_IDX_CHK_H_REVISION + 1
TOK_IDX_DB_H_PART = TOK_IDX_CHK_H_PART + 1
TOK_IDX_DB_H_CHAPTER = TOK_IDX_CHK_H_CHAPTER + 1
TOK_IDX_DB_H_SECTION = TOK_IDX_CHK_H_SECTION + 1
TOK_IDX_DB_H_FILENAME = TOK_IDX_CHK_H_FILENAME + 1
TOK_IDX_DB_H_TABLE_NAME = TOK_IDX_CHK_H_TABLE_NAME + 1
TOK_IDX_DB_H_CHECKLIST_ID = TOK_IDX_CHK_H_CHECKLIST_ID + 1
TOK_IDX_DB_H_OPTIONAL = TOK_IDX_CHK_H_OPTIONAL + 1
TOK_IDX_DB_H_STATUS = TOK_IDX_DB_H_OPTIONAL + 1
DATABASE_HEADER_TOKEN_COUNT = TOK_IDX_DB_H_STATUS + 1

TOK_IDX_DB_H_FIRST_REV = DATABASE_HEADER_TOKEN_COUNT
TOK_IDX_DB_H_FIRST_PART = TOK_IDX_DB_H_FIRST_REV + 1
TOK_IDX_DB_H_FIRST_CHAP = TOK_IDX_DB_H_FIRST_PART + 1
TOK_IDX_DB_H_FIRST_SECN = TOK_IDX_DB_H_FIRST_CHAP + 1
TOK_IDX_DB_H_TOK_COUNT = TOK_IDX_DB_H_FIRST_SECN - TOK_IDX_DB_H_FIRST_REV + 1
