#!/usr/bin/env python
# -*- coding: latin-1 -*-
"""
    File header and line header constants.

"""
OUTLINE_HEADER = "Revision, Part, Chapter, Section"

REQT_NUM_OFFSET_NONE = 0
REQT_NUM_OFFSET_CHKLIST = 1000
REQT_NUM_OFFSET_MANUAL = 5000

REQUIREMENTS_HEADER = "Revision, Part, Chapter, Section, Type, Reqt_Num, Sentence"
TOK_IDX_REQTS_REVISION = 0
TOK_IDX_REQTS_PART = 1
TOK_IDX_REQTS_CHAPTER = 2
TOK_IDX_REQTS_SECTION = 3
TOK_IDX_REQTS_TYPE = 4
TOK_IDX_REQTS_REQT_NUM = 5
TOK_IDX_REQTS_SENTENCE = 6
REQUIREMENTS_HEADER_TOKEN_COUNT = TOK_IDX_REQTS_SENTENCE + 1

MERGED_CHECKLIST_SPEC_REVS = "Keys: "
MERGED_CHECKLIST_SORTED_SPEC_REVS = "Keys sorted: "

CHECKLIST_HEADER = "Sentence, Sentence_num, Type, Revision, Part, Chapter, Section, FileName, Table_Name, Checklist_ID, Optional"
TOK_IDX_CHK_H_SENTENCE = 0
TOK_IDX_CHK_H_SENTENCE_NUM = 1
TOK_IDX_CHK_H_TYPE = 2
TOK_IDX_CHK_H_REVISION = 3
TOK_IDX_CHK_H_PART = 4
TOK_IDX_CHK_H_CHAPTER = 5
TOK_IDX_CHK_H_SECTION = 6
TOK_IDX_CHK_H_FILENAME = 7
TOK_IDX_CHK_H_TABLE_NAME = 8
TOK_IDX_CHK_H_CHECKLIST_ID = 9
TOK_IDX_CHK_H_OPTIONAL = 10
CHECKLIST_HEADER_TOKEN_COUNT = TOK_IDX_CHK_H_OPTIONAL

TOK_IDX_CHK_H_FIRST_REV = 11
TOK_IDX_MRG_CHK_H_FIRST_PART = 12
TOK_IDX_MRG_CHK_H_FIRST_CHAP = 13
TOK_IDX_MRG_CHK_H_FIRST_SECN = 13

DATABASE_HEADER = "Sentence, Const_Reference, Sentence_num, Type, Revision, Part, Chapter, Section, FileName, Table_Name, Checklist_ID, Optional"
